version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: tryton_test_db
    environment:
      POSTGRES_USER: tryton
      POSTGRES_PASSWORD: tryton
      POSTGRES_DB: tryton
    ports:
      - "5432:5432"
    volumes:
      - postgres_testdb_data_v15:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tryton"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres_testdb_data_v15: 